export const TYPOGRAPHY_VARIATIONS = {
  subtitle1: 'h6',
  subtitle2: 'h6',
  subtitle3: 'h6',
  inherit: 'p',
  body1: 'p',
  body2: 'p',
  body3: 'p',
  body4: 'p',
  body5: 'p',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
};
